name: Bug Report
description: Report bugs or issues you've encountered while playing the game
type: Bug
labels: [ "Bug", "⚠️ Triage" ]

body:
- type: checkboxes
  attributes:
    label: Prerequisites
    description: Please make sure you've completed the following steps before submitting an issue
    options:
      - label: I have searched for similar issues and confirmed this is not a duplicate
        required: true

- type: checkboxes
  attributes:
    label: Game Version
    description: Which version(s) of the game does this bug appear in?
    options:
      - label: "Command & Conquer Generals"
        required: false
      - label: "Command & Conquer Generals: Zero Hour"
        required: false
      - label: "Other (please specify below)"
        required: false

- type: textarea
  attributes:
    label: Bug Description
    description: |
      What is the bug? What happened versus what you expected to happen?
      Please provide a clear and detailed description.
  validations:
    required: true

- type: textarea
  attributes:
    label: Reproduction Steps
    description: How can we reproduce this bug?
    placeholder: |
      1. Start a new game with [specific settings]
      2. Build/Select [specific unit/building]
      3. Perform [specific action]
      4. Observe [the bug]
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional Context
    description: Add any relevant screenshots, video recordings, or other files here
  validations:
    required: false
